######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : namd_wf, Index = 0, Count = 1
# SUBMIT FILE NAME : cleanup_namd_wf_0_cori.sub
######################################################################
stream_error  = false
stream_output = false
environment = ""
+remote_cerequirements = JOBNAME=="cleanupnamdwf0c" && PASSENV==1 && WALLTIME=="00:20:00" && PROJECT=="m2187" && PRIORITY==1000 && EXTRA_ARGUMENTS=="-M escori --licenses=SCRATCH --mail-type=ALL --mail-user=georgpap@isi.com"
+remote_environment = "PEGASUS_HOME=/global/common/software/m2187/pegasus/pegasus-4.9.2dev CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=f9a4d07a-3b0b-4e6e-ad50-24e4ceb0d554 PEGASUS_WF_LABEL=namd_wf PEGASUS_DAG_JOB_ID=cleanup_namd_wf_0_cori PEGASUS_SITE=cori PEGASUS_RUNTIME=1200 PEGASUS_PROJECT=m2187 PEGASUS_QUEUE=xfer"
batch_queue = xfer
copy_to_spool = false
error = /home/georgpap/GitHub/papajim/sns-namd-shifter-example/submit/georgpap/pegasus/namd_wf/run0001//00/00/cleanup_namd_wf_0_cori.err
executable = /home/georgpap/GitHub/papajim/sns-namd-shifter-example/submit/georgpap/pegasus/namd_wf/run0001/00/00/cleanup_namd_wf_0_cori.sh
grid_resource = batch slurm papajim@cori.nersc.gov 
input = /home/georgpap/GitHub/papajim/sns-namd-shifter-example/submit/georgpap/pegasus/namd_wf/run0001//00/00/cleanup_namd_wf_0_cori.in
log = /home/georgpap/GitHub/papajim/sns-namd-shifter-example/submit/georgpap/pegasus/namd_wf/run0001/namd_wf-0.log
notification = NEVER
output = /home/georgpap/GitHub/papajim/sns-namd-shifter-example/submit/georgpap/pegasus/namd_wf/run0001//00/00/cleanup_namd_wf_0_cori.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 1000
should_transfer_files = YES
submit_event_user_notes = pool:cori
transfer_executable = true
transfer_input_files = /home/georgpap/Software/Pegasus/pegasus-4.9.2dev/share/pegasus/sh/pegasus-lite-common.sh
universe = grid
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "f9a4d07a-3b0b-4e6e-ad50-24e4ceb0d554"
+pegasus_wf_uuid = "f9a4d07a-3b0b-4e6e-ad50-24e4ceb0d554"
+pegasus_version = "4.9.2dev"
+pegasus_wf_name = "namd_wf-0"
+pegasus_wf_app = "namd_example"
+pegasus_wf_time = "20190605T153223-0700"
+pegasus_wf_xformation = "pegasus::cleanup"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "cleanup_namd_wf_0_cori"
+pegasus_job_class = 8
+pegasus_site = "cori"
+pegasus_job_runtime = 1200
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
