######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : namd_wf, Index = 0, Count = 1
# SUBMIT FILE NAME : namd2_ID0000001.sub
######################################################################
stream_error  = false
stream_output = false
environment = ""
+remote_cerequirements = JOBNAME=="namd2ID0000001" && PASSENV==1 && CORES=="32" && WALLTIME=="00:20:00" && PROJECT=="m2187" && PRIORITY==20 && EXTRA_ARGUMENTS=="--qos debug --constraint=haswell --licenses=SCRATCH --mail-type=ALL --mail-user=georgpap@isi.com --exclusive"
+remote_environment = "PEGASUS_HOME=/global/common/software/m2187/pegasus/pegasus-4.9.2dev CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=e12459cd-7b36-40e9-a4f9-1480ad4261b5 PEGASUS_WF_LABEL=namd_wf PEGASUS_DAG_JOB_ID=namd2_ID0000001 PEGASUS_SITE=cori PEGASUS_RUNTIME=1200 PEGASUS_CORES=32 PEGASUS_PROJECT=m2187"
copy_to_spool = false
error = /home/georgpap/GitHub/papajim/sns-namd-shifter-example/submit/georgpap/pegasus/namd_wf/run0001//00/00/namd2_ID0000001.err
executable = /home/georgpap/GitHub/papajim/sns-namd-shifter-example/submit/georgpap/pegasus/namd_wf/run0001/00/00/namd2_ID0000001.sh
grid_resource = batch slurm papajim@cori10.nersc.gov 
log = /home/georgpap/GitHub/papajim/sns-namd-shifter-example/submit/georgpap/pegasus/namd_wf/run0001/namd_wf-0.log
notification = NEVER
output = /home/georgpap/GitHub/papajim/sns-namd-shifter-example/submit/georgpap/pegasus/namd_wf/run0001//00/00/namd2_ID0000001.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 20
should_transfer_files = YES
submit_event_user_notes = pool:cori
transfer_executable = true
transfer_input_files = /home/georgpap/GitHub/papajim/sns-namd-shifter-example/submit/georgpap/pegasus/namd_wf/run0001/00/00/stage_in_remote_cori_0_0.meta,/home/georgpap/Software/Pegasus/pegasus-4.9.2dev/share/pegasus/sh/pegasus-lite-common.sh
universe = grid
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "e12459cd-7b36-40e9-a4f9-1480ad4261b5"
+pegasus_wf_uuid = "e12459cd-7b36-40e9-a4f9-1480ad4261b5"
+pegasus_version = "4.9.2dev"
+pegasus_wf_name = "namd_wf-0"
+pegasus_wf_app = "namd_example"
+pegasus_wf_time = "20190608T224630-0700"
+pegasus_wf_xformation = "namd2"
+pegasus_wf_dax_job_id = "ID0000001"
+pegasus_wf_dag_job_id = "namd2_ID0000001"
+pegasus_job_class = 1
+pegasus_site = "cori"
+pegasus_job_runtime = 1200
+pegasus_cores = 32
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
