######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : namd_wf, Index = 0, Count = 1
# SUBMIT FILE NAME : cleanup_namd_wf_0_cori.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=feb34f20-4d77-43de-a33d-7830a17d3347 PEGASUS_WF_LABEL=namd_wf PEGASUS_DAG_JOB_ID=cleanup_namd_wf_0_cori PEGASUS_SITE=local X509_USER_PROXY_cori=/tmp/x509up_u1001"
copy_to_spool = false
error = /home/georgepap/GitHub/papajim/sns-namd-shifter-example/submit/georgepap/pegasus/namd_wf/run0001//00/00/cleanup_namd_wf_0_cori.err
executable = /home/georgepap/pegasus-dist/pegasus-5.0.0dev/bin/pegasus-transfer
input = /home/georgepap/GitHub/papajim/sns-namd-shifter-example/submit/georgepap/pegasus/namd_wf/run0001//00/00/cleanup_namd_wf_0_cori.in
log = /home/georgepap/GitHub/papajim/sns-namd-shifter-example/submit/georgepap/pegasus/namd_wf/run0001/namd_wf-0.log
notification = NEVER
output = /home/georgepap/GitHub/papajim/sns-namd-shifter-example/submit/georgepap/pegasus/namd_wf/run0001//00/00/cleanup_namd_wf_0_cori.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 1000
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "feb34f20-4d77-43de-a33d-7830a17d3347"
+pegasus_wf_uuid = "feb34f20-4d77-43de-a33d-7830a17d3347"
+pegasus_version = "5.0.0dev"
+pegasus_wf_name = "namd_wf-0"
+pegasus_wf_app = "namd_example"
+pegasus_wf_time = "20190202T010747-0800"
+pegasus_wf_xformation = "pegasus::cleanup"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "cleanup_namd_wf_0_cori"
+pegasus_job_class = 8
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
