######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : namd_wf, Index = 0, Count = 1
# SUBMIT FILE NAME : create_dir_namd_wf_0_cori.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=6fc05261-1a3b-492b-8602-87d128b98203 PEGASUS_WF_LABEL=namd_wf PEGASUS_DAG_JOB_ID=create_dir_namd_wf_0_cori PEGASUS_SITE=local X509_USER_PROXY_cori=/tmp/x509up_u1001"
copy_to_spool = false
error = /home/georgepap/GitHub/papajim/sns-namd-shifter-example/submit/georgepap/pegasus/namd_wf/run0001//00/00/create_dir_namd_wf_0_cori.err
executable = /home/georgepap/pegasus-dist/pegasus-4.9.1dev/bin/pegasus-transfer
input = /home/georgepap/GitHub/papajim/sns-namd-shifter-example/submit/georgepap/pegasus/namd_wf/run0001//00/00/create_dir_namd_wf_0_cori.in
log = /home/georgepap/GitHub/papajim/sns-namd-shifter-example/submit/georgepap/pegasus/namd_wf/run0001/namd_wf-0.log
notification = NEVER
output = /home/georgepap/GitHub/papajim/sns-namd-shifter-example/submit/georgepap/pegasus/namd_wf/run0001//00/00/create_dir_namd_wf_0_cori.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 800
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "6fc05261-1a3b-492b-8602-87d128b98203"
+pegasus_wf_uuid = "6fc05261-1a3b-492b-8602-87d128b98203"
+pegasus_version = "4.9.1dev"
+pegasus_wf_name = "namd_wf-0"
+pegasus_wf_app = "namd_example"
+pegasus_wf_time = "20190131T162252-0800"
+pegasus_wf_xformation = "pegasus::dirmanager"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "create_dir_namd_wf_0_cori"
+pegasus_job_class = 6
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
