######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : namd_wf, Index = 0, Count = 1
# SUBMIT FILE NAME : namd2_ID0000002.sub
######################################################################
stream_error  = false
stream_output = false
environment = "PEGASUS_HOME=/project/projectdirs/m2187/sns-software/pegasus-4.9.0dev CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=feb34f20-4d77-43de-a33d-7830a17d3347 PEGASUS_WF_LABEL=namd_wf PEGASUS_DAG_JOB_ID=namd2_ID0000002 PEGASUS_SITE=cori"
copy_to_spool = false
error = /home/georgepap/GitHub/papajim/sns-namd-shifter-example/submit/georgepap/pegasus/namd_wf/run0001//00/00/namd2_ID0000002.err
executable = /home/georgepap/GitHub/papajim/sns-namd-shifter-example/submit/georgepap/pegasus/namd_wf/run0001/00/00/namd2_ID0000002.sh
globusrsl = (jobtype=single)(maxtime=20)(project=m2187)(queue=debug)
grid_resource = gt5 corigrid.nersc.gov/jobmanager-slurm
log = /home/georgepap/GitHub/papajim/sns-namd-shifter-example/submit/georgepap/pegasus/namd_wf/run0001/namd_wf-0.log
notification = NEVER
output = /home/georgepap/GitHub/papajim/sns-namd-shifter-example/submit/georgepap/pegasus/namd_wf/run0001//00/00/namd2_ID0000002.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 30
should_transfer_files = YES
submit_event_user_notes = pool:cori
transfer_error = true
transfer_executable = true
transfer_input_files = /home/georgepap/GitHub/papajim/sns-namd-shifter-example/submit/georgepap/pegasus/namd_wf/run0001/00/00/namd2_ID0000001.meta,/home/georgepap/GitHub/papajim/sns-namd-shifter-example/submit/georgepap/pegasus/namd_wf/run0001/00/00/stage_in_local_cori_0_0.meta,/home/georgepap/GitHub/papajim/sns-namd-shifter-example/submit/georgepap/pegasus/namd_wf/run0001/00/00/stage_in_local_cori_1_0.meta,/home/georgepap/pegasus-dist/pegasus-5.0.0dev/share/pegasus/sh/pegasus-lite-common.sh
transfer_output = true
universe = grid
when_to_transfer_output = ON_EXIT
x509userproxy = /tmp/x509up_u1001
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "feb34f20-4d77-43de-a33d-7830a17d3347"
+pegasus_wf_uuid = "feb34f20-4d77-43de-a33d-7830a17d3347"
+pegasus_version = "5.0.0dev"
+pegasus_wf_name = "namd_wf-0"
+pegasus_wf_app = "namd_example"
+pegasus_wf_time = "20190202T010747-0800"
+pegasus_wf_xformation = "namd2"
+pegasus_wf_dax_job_id = "ID0000002"
+pegasus_wf_dag_job_id = "namd2_ID0000002"
+pegasus_job_class = 1
+pegasus_site = "cori"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
