######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : namd_wf, Index = 0, Count = 1
# SUBMIT FILE NAME : shifter_ID0000002.sub
######################################################################
stream_error  = false
stream_output = false
environment = "PEGASUS_HOME=/project/projectdirs/m2187/sns-software/pegasus-4.9.0dev CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=27d08e86-e07e-4636-9dd3-937232b47d66 PEGASUS_WF_LABEL=namd_wf PEGASUS_DAG_JOB_ID=shifter_ID0000002 PEGASUS_SITE=cori PEGASUS_SCRATCH_DIR=/global/cscratch1/sd/papajim/georgepap/pegasus/namd_wf/run0001"
arguments = "--image=docker:papajim/namd_image:latest namd2 +p 32 production_200.conf"
copy_to_spool = false
error = /home/georgepap/GitHub/papajim/sns-namd-shifter-example/submit/georgepap/pegasus/namd_wf/run0001//00/00/shifter_ID0000002.err
executable = /usr/bin/shifter
globusrsl = (jobtype=single)(maxtime=20)(project=m2187)(queue=debug)
grid_resource = gt5 corigrid.nersc.gov/jobmanager-slurm
log = /home/georgepap/GitHub/papajim/sns-namd-shifter-example/submit/georgepap/pegasus/namd_wf/run0001/namd_wf-0.log
notification = NEVER
output = /home/georgepap/GitHub/papajim/sns-namd-shifter-example/submit/georgepap/pegasus/namd_wf/run0001//00/00/shifter_ID0000002.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 30
remote_initialdir = /global/cscratch1/sd/papajim/georgepap/pegasus/namd_wf/run0001
submit_event_user_notes = pool:cori
transfer_error = true
transfer_executable = false
transfer_output = true
universe = grid
x509userproxy = /tmp/x509up_u1001
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "27d08e86-e07e-4636-9dd3-937232b47d66"
+pegasus_wf_uuid = "27d08e86-e07e-4636-9dd3-937232b47d66"
+pegasus_version = "4.8.5dev"
+pegasus_wf_name = "namd_wf-0"
+pegasus_wf_app = "namd_example"
+pegasus_wf_time = "20190124T183810-0800"
+pegasus_wf_xformation = "shifter"
+pegasus_wf_dax_job_id = "ID0000002"
+pegasus_wf_dag_job_id = "shifter_ID0000002"
+pegasus_job_class = 1
+pegasus_site = "cori"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
